const chatExamples = [
  {
    id: "1",
    type: "text",
    content: "Hello! How can I assist you today?",
    isUser: false,
  },
  {
    id: "2",
    type: "text",
    content: "Hi! I need help with my account settings.",
    isUser: true,
  },
  {
    id: "3",
    type: "text",
    content: "Sure, could you specify the issue?",
    isUser: false,
  },
  {
    id: "4",
    type: "text",
    content: "I want to update my email address.",
    isUser: true,
  },
  {
    id: "5",
    type: "text",
    content: "No problem. Let me guide you.",
    isUser: false,
  },
  {
    id: "6",
    type: "image",
    content: "https://example.com/images/help-guide.png",
    isUser: false,
  },
  { id: "7", type: "text", content: "Thanks! That helps a lot.", isUser: true },
  {
    id: "8",
    type: "text",
    content: "You're welcome! Anything else?",
    isUser: false,
  },
  {
    id: "9",
    type: "text",
    content: "How do I reset my password?",
    isUser: true,
  },
  {
    id: "10",
    type: "text",
    content: "Click 'Forgot Password' on the login page.",
    isUser: false,
  },
  {
    id: "11",
    type: "text",
    content: "Got it. Do I need my old password?",
    isUser: true,
  },
  {
    id: "12",
    type: "text",
    content: "No, just your registered email.",
    isUser: false,
  },
  { id: "13", type: "text", content: "Perfect. Thanks!", isUser: true },
  {
    id: "14",
    type: "text",
    content: "You're welcome. Have a great day!",
    isUser: false,
  },
  {
    id: "15",
    type: "text",
    content: "Can you tell me more about your services?",
    isUser: true,
  },
  {
    id: "16",
    type: "text",
    content: "Certainly! We provide 24/7 support for various platforms.",
    isUser: false,
  },
  {
    id: "17",
    type: "text",
    content: "That's great to know. Do you offer custom solutions?",
    isUser: true,
  },
  {
    id: "18",
    type: "text",
    content: "Yes, we do. Let me send you a brochure.",
    isUser: false,
  },
  {
    id: "19",
    type: "file",
    content: "https://example.com/files/services-brochure.pdf",
    isUser: false,
  },
  {
    id: "20",
    type: "text",
    content: "Got it. I'll review this.",
    isUser: true,
  },
  {
    id: "21",
    type: "text",
    content: "Sure. Let me know if you have questions.",
    isUser: false,
  },
  {
    id: "22",
    type: "text",
    content: "What are your operating hours?",
    isUser: true,
  },
  {
    id: "23",
    type: "text",
    content: "We operate 24/7, every day.",
    isUser: false,
  },
  {
    id: "24",
    type: "text",
    content: "That's convenient. Do you offer live chat support?",
    isUser: true,
  },
  {
    id: "25",
    type: "text",
    content: "Yes, we do! You're chatting with us now.",
    isUser: false,
  },
  { id: "26", type: "text", content: "Haha, fair point!", isUser: true },
  {
    id: "27",
    type: "text",
    content: "Anything else I can assist you with?",
    isUser: false,
  },
  {
    id: "28",
    type: "text",
    content: "Not at the moment. Thanks for your help.",
    isUser: true,
  },
  {
    id: "29",
    type: "text",
    content: "You're welcome. Have a wonderful day!",
    isUser: false,
  },
  { id: "30", type: "text", content: "Thanks. You too!", isUser: true },
];

export default chatExamples;
