const data = {
  chapter_count: 13,
  chapter_details: [
    {
      chapter_number: "1",
      chapter_source: "0758CH01.pdf",
      chapter_name: "Nutrition in Plants",
      section_count: 3,
      section_list: [
        "MODE OF NUTRITION",
        "PHOTOSYNTHESIS",
        "OTHER MODES OF NUTRITION",
      ],
    },
    {
      chapter_number: "2",
      chapter_source: "0758CH02.pdf",
      chapter_name: "Nutrition in Animals",
      section_count: 4,
      section_list: [
        "WAYS OF TAKING FOOD",
        "DIGESTION IN HUMANS",
        "DIGESTION IN GRASS-EATING ANIMALS",
        "FEEDING IN AMOEBA",
      ],
    },
    {
      chapter_number: "3",
      chapter_source: "0758CH04.pdf",
      chapter_name: "Heat",
      section_count: 3,
      section_list: [
        "HOT AND COLD",
        "MEASURING TEMPERATURE",
        "TRANSFER OF HEAT",
      ],
    },
    {
      chapter_number: "4",
      chapter_source: "0758CH05.pdf",
      chapter_name: "Acids, Bases and Salts",
      section_count: 3,
      section_list: ["ACIDS AND BASES", "NATURAL INDICATORS", "NEUTRALISATION"],
    },
    {
      chapter_number: "5",
      chapter_source: "0758CH06.pdf",
      chapter_name: "Physical and Chemical Changes",
      section_count: 3,
      section_list: ["PHYSICAL CHANGES", "CHEMICAL CHANGE", "RUSTING OF IRON"],
    },
    {
      chapter_number: "6",
      chapter_source: "0758CH10.pdf",
      chapter_name: "Respiration in Organisms",
      section_count: 5,
      section_list: [
        "WHY DO WE RESPIRE?",
        "BREATHING",
        "HOW DO WE BREATHE?",
        "BREATHE OUT?",
        "OTHER ANIMALS",
      ],
    },
    {
      chapter_number: "7",
      chapter_source: "0758CH11.pdf",
      chapter_name: "Transportation in Animals and Plants",
      section_count: 3,
      section_list: [
        "CIRCULATORY SYSTEM",
        "EXCRETION IN ANIMALS",
        "TRANSPORT OF SUBSTANCES",
      ],
    },
    {
      chapter_number: "8",
      chapter_source: "0758CH12.pdf",
      chapter_name: "Reproduction in Plants",
      section_count: 5,
      section_list: [
        "MODES OF REPRODUCTION",
        "ASEXUAL REPRODUCTION",
        "SEXUAL REPRODUCTION",
        "FRUITS AND SEED FORMATION",
        "SEED DISPERSAL",
      ],
    },
    {
      chapter_number: "9",
      chapter_source: "0758CH13.pdf",
      chapter_name: "Motion and Time",
      section_count: 4,
      section_list: [
        "SLOW OR FAST",
        "SPEED",
        "MEASUREMENT OF TIME",
        "DISTANCE-TIME GRAPH",
      ],
    },
    {
      chapter_number: "10",
      chapter_source: "0758CH14.pdf",
      chapter_name: "Electric Current and its Effects",
      section_count: 4,
      section_list: [
        "SYMBOLS OF ELECTRIC COMPONENTS",
        "HEATING EFFECT",
        "MAGNETIC EFFECT",
        "ELECTRIC BELL",
      ],
    },
    {
      chapter_number: "11",
      chapter_source: "0758CH15.pdf",
      chapter_name: "Light",
      section_count: 5,
      section_list: [
        "LIGHT TRAVELS",
        "REFLECTION OF LIGHT",
        "RIGHT OR LEFT!",
        "SPHERICAL MIRRORS",
        "SUNLIGHT",
      ],
    },
    {
      chapter_number: "12",
      chapter_source: "0758CH17.pdf",
      chapter_name: "Forests: Our Lifeline",
      section_count: 3,
      section_list: [
        "VISIT TO A FOREST",
        "SOME FOREST PLANTS",
        "AQUATIC ORGANISMS",
      ],
    },
    {
      chapter_number: "13",
      chapter_source: "0758CH18.pdf",
      chapter_name: "Wastewater Story",
      section_count: 3,
      section_list: [
        "WATER, OUR LIFELINE",
        "WHAT IS SEWAGE?",
        "WASTEWATER TREATMENT",
      ],
    },
  ],
};

export default data;
